name: r-base # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.0.1.20190611-2' # just for humans, typically '1.2+git' or '1.3.2'
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict
summary: The R Language and Environment # 79 char long summary
description: |
  First steps towards packaging R as snap, starting with a basic 3.6.0 build.
  You have a paragraph or two to tell the most important story about your snap.
  Keep it under 100 words though, we live in tweetspace and your description
  wants to look good in the snap store.

apps:
  r-base:
    command: usr/bin/R
#    environment:
#      LC_ALL: en_US.UTF-8
#      LANG: en_US.UTF-8
    plugs:
      - home
      - desktop
      - desktop-legacy
      - network
      - unity7
      - wayland
      - x11

  r-script:
    command: usr/bin/Rscript
#    environment:
#      LC_ALL: en_US.UTF-8
#      LANG: en_US.UTF-8
    plugs:
      - home
      - desktop
      - desktop-legacy
      - network
      - unity7
      - wayland
      - x11

parts:
  pre-conf:
    source: snap/local/config/
    plugin: dump
    organize:
      Rprofile.site: usr/lib/R/etc/Rprofile.site
      Renviron.site: usr/lib/R/etc/Renviron.site
    after: 
      - r-base

  r-base:
    # See 'snapcraft plugins'
    plugin: autotools
    source: http://cloud.r-project.org/src/base/R-3/R-3.6.0.tar.gz
    build-environment:
      - LANG: C.UTF-8
      - LC_ALL: C.UTF-8
    build-packages:
      #- locales
      - g++
      - gcc
      - gfortran
      - libbz2-dev 
      - libcairo2-dev 
      - libcurl4-openssl-dev
      - libjpeg-dev 
      - liblzma-dev
      - libpango1.0-dev 
      - libpcre3-dev
      - libpng-dev 
      - libreadline-dev
      - libtiff5-dev 
      - libx11-dev 
      - libxt-dev 
      - x11proto-core-dev 
      - xauth 
      - xfonts-base
      - xvfb 
      - zlib1g-dev
    configflags:
      - --with-readline=yes
      - --with-x=yes
      - --prefix=/snap/r-base/current/usr
    organize:
      snap/r-base/current/usr: usr
    #override-build: |
    #  snapcraftctl build
    #  sed -i 's|root/parts/r-base/install/usr|usr|g' \
    #  		parts/r-base/install/snap/r-base/current/usr/lib/R/etc/Makeconf
    override-build: |
      snapcraftctl build
      sed -i 's|root/parts/r-base/install/usr|/snap/r-base/current/usr|g' $SNAPCRAFT_PART_INSTALL/snap/r-base/current/usr/lib/R/etc/Makeconf
    stage-packages:
      - build-essential
      - gfortran
      - libasn1-8-heimdal
      - libcurl4
      - libgfortran4
      - libbsd0
      - libbz2-1.0
      - libcairo2
      - libc6-dev
      - libdatrie1
      - libexpat1
      - libffi6
      - libfontconfig1
      - libfreetype6
      - libfribidi0
      - libgcc1
      - libgfortran5
      - libglib2.0-0
      - libgomp1
      - libgraphite2-3
      - libharfbuzz0b
      - libice6
      - libicu60
      - libjbig0
      - libjpeg-turbo8
      - liblzma5
      - libopenblas-base
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpcre3
      - libpixman-1-0
      - libpng16-16
      - libquadmath0
      - libreadline7
      - libsm6
      - libstdc++6
      - libstdc++-7-dev
      - libthai0
      - libtiff5
      - libtinfo5
      - libuuid1
      - libwebp6
      - libx11-6
      - libxau6
      - libxcb1
      - libxcb-render0
      - libxcb-shm0
      - libxdmcp6
      - libxext6
      - libxrender1
      - libxt6
      - libzstd1
      #- locales-all
      - xfonts-base
      - zlib1g
