name: r-base                # you probably want to 'snapcraft register <name>'
base: core18                # the base snap is the execution environment for this snap
version: '0.0.1.20190614-1' # just for humans, typically '1.2+git' or '1.3.2'
grade: devel                # must be 'stable' to release into candidate/stable channels
confinement: strict
summary: The R Language and Environment # 79 char long summary
description: |
  R is a system for statistical computation and graphics.  It consists
  of a language plus a run-time environment with graphics, a debugger,
  access to certain system functions, and the ability to run programs
  stored in script files.
  
apps:
  r-base:
    command: usr/bin/R
    environment:
      SHLIB_LIBADD: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET"
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET"
    plugs:
      - home
      - desktop
      - desktop-legacy
      - network
      - unity7
      - wayland
      - x11
  r-script:
    command: usr/bin/Rscript
    plugs:
      - home
      - desktop
      - desktop-legacy
      - network
      - unity7
      - wayland
      - x11
  shell:
    command: bin/bash
    environment:
      SHLIB_LIBADD: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET"
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET"
    plugs:
      - home
      - desktop
      - desktop-legacy
      - network
      - unity7
      - wayland
      - x11

parts:
  pre-conf:
    source: snap/local/config/
    plugin: dump
    organize:
      Rprofile.site: usr/lib/R/etc/Rprofile.site
      Renviron.site: usr/lib/R/etc/Renviron.site
    after: 
      - r-base

  r-base:
    # See 'snapcraft plugins'
    plugin: autotools
    source: http://cloud.r-project.org/src/base/R-3/R-3.6.0.tar.gz
    build-environment:
      - LANG: C.UTF-8
      - LC_ALL: C.UTF-8
    build-packages:
      #- locales
      - g++
      - gcc
      - gfortran
      - libbz2-dev 
      - libcairo2-dev 
      - libcurl4-openssl-dev
      - libjpeg-dev 
      - liblzma-dev
      - libpango1.0-dev 
      - libpcre3-dev
      - libpng-dev 
      - libreadline-dev
      - libtiff5-dev 
      - libx11-dev 
      - libxt-dev
      - tcl8.6-dev
      - tk8.6-dev
      - x11proto-core-dev 
      - xauth 
      - xfonts-base
      - xvfb 
      - zlib1g-dev
    configflags:
      - --prefix=/snap/r-base/current/usr
      - --disable-nls
      - --enable-BLAS-shlib
      - --enable-R-profiling
      - --enable-R-shlib
      - --enable-memory-profiling
      - --with-readline=yes
      - --with-x=yes
    organize:
      snap/r-base/current/usr: usr
    override-build: |
      snapcraftctl build
      sed -i 's|root/parts/r-base/install|/snap/r-base/current|g' $SNAPCRAFT_PART_INSTALL/snap/r-base/current/usr/lib/R/etc/Makeconf
    stage-packages:
      - bash
      - build-essential
      - gfortran
      - libasn1-8-heimdal
      - libcurl4
      - libgfortran4
      - libbsd0
      - libbz2-1.0
      - libcairo2
      - libc6-dev
      - libdatrie1
      - libexpat1
      - libffi6
      - libfontconfig1
      - libfreetype6
      - libfribidi0
      - libgcc1
      - libgfortran5
      - libglib2.0-0
      - libgomp1
      - libgraphite2-3
      - libharfbuzz0b
      - libice6
      - libicu60
      - libjbig0
      - libjpeg-turbo8
      - liblzma5
      - libopenblas-base
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpcre3
      - libpixman-1-0
      - libpng16-16
      - libquadmath0
      - libreadline7
      - libsm6
      - libstdc++6
      - libstdc++-7-dev
      - libtcl8.6
      - libtk8.6
      - libthai0
      - libtiff5
      - libtinfo5
      - libuuid1
      - libwebp6
      - libx11-6
      - libxau6
      - libxcb1
      - libxcb-render0
      - libxcb-shm0
      - libxdmcp6
      - libxext6
      - libxft2
      - libxrender1
      - libxss1
      - libxt6
      - libzstd1
      #- locales-all
      - xfonts-base
      - zlib1g
